//-----------------------------------------------------------
// Debug Info - Namespace Scopes
//-----------------------------------------------------------

.decl di?namespace(entry:DINamespace)
.decl di?namespace_name(entry:DINamespace, name:symbol)
.decl di?namespace_line(entry:DINamespace, line:Line)
.decl di?namespace_source_file(entry:DINamespace, file:DIFile)
.decl di?namespace_scope(entry:DINamespace, scope:DIScope)

di?scope(e) :- di?namespace(e).
