.decl _clause(c:Constant)
.decl _catch_clause(c:Constant)
.decl _filter_clause(c:Constant)
.decl _landingpad_instr_clause(instr:LandingPadInstruction, i:number, c:Constant)

_clause(Constant) :- clause(Clause), Clause = [Constant].
_catch_clause(Constant)  :- catch_clause(Clause), Clause = [Constant].
_filter_clause(Constant) :- filter_clause(Clause), Clause = [Constant].
_landingpad_instr_clause(Instr, Idx, Constant) :-
   landingpad_instr_clause(Instr, Idx, Clause), Clause = [Constant].