.decl _clause(c:Constant)
.decl _catch_clause(c:Constant)
.decl _filter_clause(c:Constant)
.decl _landingpad_instr_clause(instr:LandingPadInstruction, i:number, c:Constant)

_clause(Clause) :- clause(Clause).
_catch_clause(Clause)  :- catch_clause(Clause).
_filter_clause(Clause) :- filter_clause(Clause).
_landingpad_instr_clause(Instr, Idx, Clause) :-
   landingpad_instr_clause(Instr, Idx, Clause).